"""
Auto-Post Module

Creates automated discussion posts after AI summary generation.
Uses sync DB sessions (called from ingestion scripts).
"""

import json
from sqlalchemy import select
from app.models import (
    Session,
    SessionResult,
    SessionSummary,
    Driver,
    Team,
    Post,
    PostType,
    Tag,
    User,
)

BOT_USERNAME = "lapwise-bot"

SESSION_TYPE_LABELS = {
    "race": "Race",
    "qualifying": "Qualifying",
    "sprint_race": "Sprint Race",
    "sprint_qualifying": "Sprint Qualifying",
    "fp1": "Free Practice 1",
    "fp2": "Free Practice 2",
    "fp3": "Free Practice 3",
}

TAG_COLORS = {
    "race-report": "#A020F0",
    "qualifying-report": "#3B82F6",
    "sprint-report": "#EAB308",
    "practice-report": "#22C55E",
    "ai-summary": "#EC4899",
}


def create_auto_post(db, session_id, summary: SessionSummary) -> int | None:
    """
    Create an automated discussion post from a session summary.

    Returns the created post ID, or None if creation fails.
    """
    # Load session
    session = db.execute(
        select(Session).where(Session.id == session_id)
    ).scalar_one_or_none()
    if not session:
        print(f"  ✗ Session {session_id} not found for auto-post")
        return None

    # Get bot user
    bot = db.execute(
        select(User).where(User.username == BOT_USERNAME)
    ).scalar_one_or_none()
    if not bot:
        print(f"  ✗ Bot user '{BOT_USERNAME}' not found. Run seed_bot_user.py first.")
        return None

    # Load top 10 results for the post body
    results = db.execute(
        select(SessionResult, Driver, Team)
        .join(Driver, SessionResult.driver_id == Driver.id)
        .join(Team, SessionResult.team_id == Team.id)
        .where(SessionResult.session_id == session_id)
        .order_by(SessionResult.position)
        .limit(10)
    ).all()

    # Parse key facts
    try:
        key_facts = json.loads(summary.key_facts)
    except (json.JSONDecodeError, TypeError):
        key_facts = []

    # Build post
    session_label = SESSION_TYPE_LABELS.get(session.session_type, session.session_type)
    title = f"{session.event_name} {session_label} Report"
    body = _build_post_body(session, session_label, key_facts, summary, results)

    # Get or create tags
    tag_ids = _get_or_create_tags(db, session, bot.id)

    # Create post
    post = Post(
        author_id=bot.id,
        title=title,
        body=body,
        post_type=PostType.news,
        is_pinned=True,
    )
    if tag_ids:
        tags = db.execute(select(Tag).where(Tag.id.in_(tag_ids))).scalars().all()
        post.tags = list(tags)

    db.add(post)
    db.commit()
    db.refresh(post)

    # Link summary to post
    summary.post_id = post.id
    db.commit()

    print(f"  ✓ Auto-posted: {title} (post_id={post.id})")
    return post.id


def _build_post_body(session, session_label, key_facts, summary, results):
    """Build the markdown body for the auto-post."""
    season = session.year
    round_num = session.round
    session_type = session.session_type

    # Top 3 moments
    moments = ""
    for i, fact in enumerate(key_facts[:3], 1):
        moments += f"{i}. **{fact['headline']}** — {fact['detail']}\n"

    featured_embed = _select_featured_embed(session, key_facts, results)
    results_embed = _select_results_embed(session)
    discussion_question = _build_discussion_question(session, key_facts)

    # Links section
    links = _build_links(season, round_num, session_type)

    body = f"""## {session_label} Highlights

{moments}
## Summary

{summary.summary_text}

## Featured Chart

{featured_embed}

## Results

{results_embed}

## Your Take

{discussion_question}

## Dive Deeper

{links}

---
*Generated by Clutch AI*"""

    return body


def _facts_text(key_facts):
    """Flatten key facts into lowercase searchable text."""
    parts = []
    for fact in key_facts:
        if isinstance(fact, dict):
            parts.append(str(fact.get("headline", "")))
            parts.append(str(fact.get("detail", "")))
    return " ".join(parts).lower()


def _top_driver_codes(results, limit=3):
    """Return top finishing driver codes for chart defaults."""
    codes = []
    for row in results[:limit]:
        driver = row.Driver
        code = driver.driver_code or driver.full_name
        if code:
            codes.append(code)
    return ",".join(codes)


def _select_featured_embed(session, key_facts, results):
    """Choose one relevant discussion-page chart embed for the session report."""
    season = session.year
    round_num = session.round
    session_type = session.session_type
    is_sprint = "true" if session_type == "sprint_race" else "false"
    facts = _facts_text(key_facts)
    top_codes = _top_driver_codes(results)

    if session_type in ("race", "sprint_race"):
        if any(
            token in facts
            for token in (
                "safety car",
                " vsc",
                "pit",
                "strategy",
                "undercut",
                "overcut",
                "tyre",
                "tire",
            )
        ):
            return (
                f'::lapwise-chart{{type="pit-stop-delta" season={season} '
                f"round={round_num} isSprint={is_sprint} "
                f'title="Pit Stop Timing"}}'
            )

        if any(
            token in facts
            for token in ("lead", "lap 1", "recovery", "recovered", "position")
        ):
            return (
                f'::lapwise-chart{{type="position-battle" season={season} '
                f'round={round_num} isSprint={is_sprint} view="position" '
                f'drivers="{top_codes}" title="Position Battle"}}'
            )

        if "fastest lap" in facts:
            return (
                f'::lapwise-chart{{type="fastest-lap-timeline" season={season} '
                f"round={round_num} isSprint={is_sprint} "
                f'title="Fastest Lap Timeline"}}'
            )

        return (
            f'::lapwise-chart{{type="position-battle" season={season} '
            f'round={round_num} isSprint={is_sprint} view="position" '
            f'drivers="{top_codes}" title="Position Battle"}}'
        )

    if session_type in ("qualifying", "sprint_qualifying"):
        is_sprint = "true" if session_type == "sprint_qualifying" else "false"
        return (
            f'::lapwise-chart{{type="qualifying-progression" season={season} '
            f"round={round_num} isSprint={is_sprint} "
            f'title="Qualifying Progression"}}'
        )

    if session_type in ("fp1", "fp2", "fp3"):
        practice_session = int(session_type[-1])
        return (
            f'::lapwise-chart{{type="lap-time-by-lap" season={season} '
            f"round={round_num} practiceSession={practice_session} "
            f'view="lapTime" drivers="{top_codes}" title="Practice Lap Times"}}'
        )

    return (
        f'::lapwise-chart{{type="race-pace-evolution" season={season} '
        f'round={round_num} title="Session Pace Evolution"}}'
    )


def _select_results_embed(session):
    """Choose a safe results embed for discussion pages."""
    if session.session_type in ("race", "sprint_race"):
        is_sprint = "true" if session.session_type == "sprint_race" else "false"
        return (
            f'::lapwise-table{{type="race-results" season={session.year} '
            f"round={session.round} isSprint={is_sprint} limit=10 "
            f'title="Top 10 Results"}}'
        )
    return _build_links(session.year, session.round, session.session_type)


def _build_discussion_question(session, key_facts):
    """Create a simple prompt that invites replies."""
    facts = _facts_text(key_facts)

    if "safety car" in facts or "pit" in facts or "strategy" in facts:
        return "Was this result decided more by race pace, pit timing, or the neutralized period?"
    if "lead" in facts or "recovery" in facts or "position" in facts:
        return "Which position swing mattered most in deciding the result?"
    if session.session_type in ("qualifying", "sprint_qualifying"):
        return "Which qualifying performance do you think mattered most for the rest of the weekend?"
    if session.session_type in ("fp1", "fp2", "fp3"):
        return "Which long-run or setup trend are you watching after this session?"
    return "What stood out most to you from this session?"


def _build_race_table(results):
    """Build a markdown results table for race/sprint."""
    lines = [
        "| Pos | Driver | Team | Time | Pts |",
        "| --- | ------ | ---- | ---- | --- |",
    ]
    for row in results:
        sr = row.SessionResult
        driver = row.Driver
        team = row.Team
        time_str = f"{sr.time_seconds:.3f}s" if sr.time_seconds else sr.status or "—"
        pts = sr.points if sr.points else "—"
        fl = " ⚡" if sr.fastest_lap else ""
        lines.append(
            f"| P{sr.position} | {driver.full_name}{fl} | {team.name} | {time_str} | {pts} |"
        )
    return "\n".join(lines)


def _build_qualifying_table(results):
    """Build a markdown results table for qualifying."""
    lines = [
        "| Pos | Driver | Team | Best Time |",
        "| --- | ------ | ---- | --------- |",
    ]
    for row in results:
        sr = row.SessionResult
        driver = row.Driver
        team = row.Team
        best = sr.q3_time_seconds or sr.q2_time_seconds or sr.q1_time_seconds
        time_str = f"{best:.3f}s" if best else "—"
        lines.append(
            f"| P{sr.position} | {driver.full_name} | {team.name} | {time_str} |"
        )
    return "\n".join(lines)


def _build_practice_table(results):
    """Build a markdown results table for practice."""
    lines = ["| Pos | Driver | Team | Best Lap |", "| --- | ------ | ---- | -------- |"]
    for row in results:
        sr = row.SessionResult
        driver = row.Driver
        team = row.Team
        time_str = f"{sr.time_seconds:.3f}s" if sr.time_seconds else "—"
        lines.append(
            f"| P{sr.position} | {driver.full_name} | {team.name} | {time_str} |"
        )
    return "\n".join(lines)


def _build_links(season, round_num, session_type):
    """Build links to interactive charts on the results page."""
    base = f"/results/{season}/{round_num}"
    if session_type in ("race", "sprint_race"):
        return (
            f"- [Lap Time Analysis]({base}?tab=analysis)\n"
            f"- [Strategy Breakdown]({base}?tab=strategy)\n"
            f"- [Full Results]({base})"
        )
    elif session_type in ("qualifying", "sprint_qualifying"):
        return (
            f"- [Sector Comparison]({base}?tab=qualifying)\n"
            f"- [Full Analysis]({base}?tab=analysis)\n"
            f"- [Full Results]({base})"
        )
    elif session_type in ("fp1", "fp2", "fp3"):
        return f"- [Practice Data]({base}?tab=practice)\n" f"- [Full Results]({base})"
    return f"- [Full Results]({base})"


def _get_or_create_tags(db, session, bot_user_id):
    """Get or create tags for the auto-post."""
    session_type = session.session_type
    tag_ids = []

    # Session type tag
    if session_type in ("race", "sprint_race"):
        tag_slug = "race-report"
        tag_name = "Race Report"
    elif session_type in ("qualifying", "sprint_qualifying"):
        tag_slug = "qualifying-report"
        tag_name = "Qualifying Report"
    elif session_type in ("fp1", "fp2", "fp3"):
        tag_slug = "practice-report"
        tag_name = "Practice Report"
    else:
        tag_slug = "report"
        tag_name = "Report"

    tag_id = _ensure_tag(db, tag_slug, tag_name, bot_user_id)
    if tag_id:
        tag_ids.append(tag_id)

    # AI summary tag
    ai_tag_id = _ensure_tag(db, "ai-summary", "AI Summary", bot_user_id)
    if ai_tag_id:
        tag_ids.append(ai_tag_id)

    return tag_ids


def _ensure_tag(db, slug, name, created_by_id):
    """Get existing tag by slug or create it."""
    tag = db.execute(select(Tag).where(Tag.slug == slug)).scalar_one_or_none()

    if tag:
        return tag.id

    color = TAG_COLORS.get(slug, "#6B7280")
    tag = Tag(
        name=name,
        slug=slug,
        color=color,
        category="topic",
        created_by=created_by_id,
    )
    db.add(tag)
    db.commit()
    db.refresh(tag)
    return tag.id
