"""Refactor to session-based schema with year-partitioned teams

Revision ID: 6398898cc337
Revises: e65d667f4326
Create Date: 2025-11-02 22:52:46.249694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6398898cc337"
down_revision: Union[str, None] = "e65d667f4326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old tables first (with CASCADE to handle foreign keys)
    op.drop_index("ix_race_results_driver_id", table_name="race_results")
    op.drop_index("ix_race_results_id", table_name="race_results")
    op.drop_index("ix_race_results_race_id", table_name="race_results")
    op.drop_index("ix_race_results_team_id", table_name="race_results")
    op.drop_table("race_results")
    op.drop_index("ix_races_id", table_name="races")
    op.drop_index("ix_races_season", table_name="races")
    op.drop_table("races")

    # Create new tables
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("circuit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["circuit_id"], ["circuits.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "year", "round", "session_type", name="uq_year_round_session"
        ),
    )
    op.create_index(
        "idx_year_session_type", "sessions", ["year", "session_type"], unique=False
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index(op.f("ix_sessions_year"), "sessions", ["year"], unique=False)
    op.create_table(
        "session_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("headshot_url", sa.String(), nullable=True),
        sa.Column("grid_position", sa.Integer(), nullable=True),
        sa.Column("points", sa.Float(), nullable=True),
        sa.Column("laps_completed", sa.Integer(), nullable=True),
        sa.Column("time_seconds", sa.Float(), nullable=True),
        sa.Column("fastest_lap", sa.Boolean(), nullable=True),
        sa.Column("q1_time_seconds", sa.Float(), nullable=True),
        sa.Column("q2_time_seconds", sa.Float(), nullable=True),
        sa.Column("q3_time_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "driver_id", name="uq_session_driver"),
    )
    op.create_index("idx_driver_id", "session_results", ["driver_id"], unique=False)
    op.create_index("idx_session_id", "session_results", ["session_id"], unique=False)
    op.create_index(
        op.f("ix_session_results_driver_id"),
        "session_results",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_results_id"), "session_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_session_results_session_id"),
        "session_results",
        ["session_id"],
        unique=False,
    )

    # Update existing tables
    op.add_column("circuits", sa.Column("track_length_km", sa.Float(), nullable=True))
    op.add_column(
        "drivers", sa.Column("driver_code", sa.String(length=3), nullable=False)
    )
    op.drop_constraint("drivers_abbreviation_key", "drivers", type_="unique")
    op.create_unique_constraint(None, "drivers", ["driver_code"])
    op.drop_column("drivers", "default_headshot_url")
    op.drop_column("drivers", "abbreviation")
    op.add_column("teams", sa.Column("year", sa.Integer(), nullable=False))
    op.alter_column(
        "teams",
        "team_color",
        existing_type=sa.VARCHAR(length=7),
        type_=sa.String(length=6),
        existing_nullable=True,
    )
    op.drop_constraint("teams_name_key", "teams", type_="unique")
    op.create_index("idx_team_year", "teams", ["year"], unique=False)
    op.create_index(op.f("ix_teams_year"), "teams", ["year"], unique=False)
    op.create_unique_constraint("uq_team_year_name", "teams", ["year", "name"])
    op.drop_column("teams", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("country", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    )
    op.drop_constraint("uq_team_year_name", "teams", type_="unique")
    op.drop_index(op.f("ix_teams_year"), table_name="teams")
    op.drop_index("idx_team_year", table_name="teams")
    op.create_unique_constraint("teams_name_key", "teams", ["name"])
    op.alter_column(
        "teams",
        "team_color",
        existing_type=sa.String(length=6),
        type_=sa.VARCHAR(length=7),
        existing_nullable=True,
    )
    op.drop_column("teams", "year")
    op.add_column(
        "drivers",
        sa.Column(
            "abbreviation", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "drivers",
        sa.Column(
            "default_headshot_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "drivers", type_="unique")
    op.create_unique_constraint("drivers_abbreviation_key", "drivers", ["abbreviation"])
    op.drop_column("drivers", "driver_code")
    op.drop_column("circuits", "track_length_km")
    op.create_table(
        "race_results",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("driver_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("grid_position", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "points",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("time", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("fastest_lap", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("fastest_lap_time", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "fastest_lap_number", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("headshot_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name="race_results_driver_id_fkey",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
            name="race_results_race_id_fkey",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="race_results_team_id_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="race_results_pkey"),
    )
    op.create_index(
        "ix_race_results_team_id", "race_results", ["team_id"], unique=False
    )
    op.create_index(
        "ix_race_results_race_id", "race_results", ["race_id"], unique=False
    )
    op.create_index("ix_race_results_id", "race_results", ["id"], unique=False)
    op.create_index(
        "ix_race_results_driver_id", "race_results", ["driver_id"], unique=False
    )
    op.create_table(
        "races",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("round", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "event_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("circuit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuits.id"],
            name="races_circuit_id_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="races_pkey"),
    )
    op.create_index("ix_races_season", "races", ["season"], unique=False)
    op.create_index("ix_races_id", "races", ["id"], unique=False)
    op.drop_index(op.f("ix_session_results_session_id"), table_name="session_results")
    op.drop_index(op.f("ix_session_results_id"), table_name="session_results")
    op.drop_index(op.f("ix_session_results_driver_id"), table_name="session_results")
    op.drop_index("idx_session_id", table_name="session_results")
    op.drop_index("idx_driver_id", table_name="session_results")
    op.drop_table("session_results")
    op.drop_index(op.f("ix_sessions_year"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_index("idx_year_session_type", table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
