"""Initial schema: drivers, teams, circuits, races, race_results

Revision ID: e65d667f4326
Revises: 
Create Date: 2025-10-25 16:15:07.023983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e65d667f4326"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_circuits_id"), "circuits", ["id"], unique=False)
    op.create_table(
        "drivers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(length=3), nullable=False),
        sa.Column("driver_number", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.String(length=3), nullable=True),
        sa.Column("default_headshot_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abbreviation"),
    )
    op.create_index(op.f("ix_drivers_id"), "drivers", ["id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("team_color", sa.String(length=7), nullable=True),
        sa.Column("country", sa.String(length=3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("event_date", sa.DateTime(), nullable=True),
        sa.Column("circuit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["circuit_id"], ["circuits.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_races_id"), "races", ["id"], unique=False)
    op.create_index(op.f("ix_races_season"), "races", ["season"], unique=False)
    op.create_table(
        "race_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("grid_position", sa.Integer(), nullable=True),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("time", sa.String(), nullable=True),
        sa.Column("fastest_lap", sa.Boolean(), nullable=False),
        sa.Column("fastest_lap_time", sa.String(), nullable=True),
        sa.Column("fastest_lap_number", sa.Integer(), nullable=True),
        sa.Column("headshot_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["race_id"], ["races.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_race_results_driver_id"), "race_results", ["driver_id"], unique=False
    )
    op.create_index(op.f("ix_race_results_id"), "race_results", ["id"], unique=False)
    op.create_index(
        op.f("ix_race_results_race_id"), "race_results", ["race_id"], unique=False
    )
    op.create_index(
        op.f("ix_race_results_team_id"), "race_results", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_race_results_team_id"), table_name="race_results")
    op.drop_index(op.f("ix_race_results_race_id"), table_name="race_results")
    op.drop_index(op.f("ix_race_results_id"), table_name="race_results")
    op.drop_index(op.f("ix_race_results_driver_id"), table_name="race_results")
    op.drop_table("race_results")
    op.drop_index(op.f("ix_races_season"), table_name="races")
    op.drop_index(op.f("ix_races_id"), table_name="races")
    op.drop_table("races")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_drivers_id"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_circuits_id"), table_name="circuits")
    op.drop_table("circuits")
    # ### end Alembic commands ###
