"""Add lap timing, weather, track status, and race control message tables

Revision ID: fb3475803d53
Revises: a00adb9757a9
Create Date: 2025-12-22 10:13:09.580320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb3475803d53"
down_revision: Union[str, None] = "a00adb9757a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("lap_number", sa.Integer(), nullable=False),
        sa.Column("lap_time_seconds", sa.Float(), nullable=True),
        sa.Column("sector1_time_seconds", sa.Float(), nullable=True),
        sa.Column("sector2_time_seconds", sa.Float(), nullable=True),
        sa.Column("sector3_time_seconds", sa.Float(), nullable=True),
        sa.Column("lap_start_time_seconds", sa.Float(), nullable=True),
        sa.Column("sector1_session_time_seconds", sa.Float(), nullable=True),
        sa.Column("sector2_session_time_seconds", sa.Float(), nullable=True),
        sa.Column("sector3_session_time_seconds", sa.Float(), nullable=True),
        sa.Column("pit_in_time_seconds", sa.Float(), nullable=True),
        sa.Column("pit_out_time_seconds", sa.Float(), nullable=True),
        sa.Column("stint", sa.Integer(), nullable=True),
        sa.Column("speed_i1", sa.Float(), nullable=True),
        sa.Column("speed_i2", sa.Float(), nullable=True),
        sa.Column("speed_fl", sa.Float(), nullable=True),
        sa.Column("speed_st", sa.Float(), nullable=True),
        sa.Column("compound", sa.String(length=10), nullable=True),
        sa.Column("tyre_life", sa.Integer(), nullable=True),
        sa.Column("fresh_tyre", sa.Boolean(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("track_status", sa.String(length=10), nullable=True),
        sa.Column("is_personal_best", sa.Boolean(), nullable=True),
        sa.Column("is_accurate", sa.Boolean(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_reason", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "driver_id", "lap_number", name="uq_session_driver_lap"
        ),
    )
    op.create_index(
        "idx_laps_session_driver", "laps", ["session_id", "driver_id"], unique=False
    )
    op.create_index(
        "idx_laps_session_lap_number",
        "laps",
        ["session_id", "lap_number"],
        unique=False,
    )
    op.create_index(op.f("ix_laps_driver_id"), "laps", ["driver_id"], unique=False)
    op.create_index(op.f("ix_laps_id"), "laps", ["id"], unique=False)
    op.create_index(op.f("ix_laps_session_id"), "laps", ["session_id"], unique=False)
    op.create_table(
        "race_control_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("session_time_seconds", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("driver_number", sa.Integer(), nullable=True),
        sa.Column("flag", sa.String(length=20), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.Integer(), nullable=True),
        sa.Column("lap_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_race_control_session_driver",
        "race_control_messages",
        ["session_id", "driver_number"],
        unique=False,
    )
    op.create_index(
        "idx_race_control_session_time",
        "race_control_messages",
        ["session_id", "session_time_seconds"],
        unique=False,
    )
    op.create_index(
        op.f("ix_race_control_messages_id"),
        "race_control_messages",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_race_control_messages_session_id"),
        "race_control_messages",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "track_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("session_time_seconds", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_track_status_session_time",
        "track_status",
        ["session_id", "session_time_seconds"],
        unique=False,
    )
    op.create_index(op.f("ix_track_status_id"), "track_status", ["id"], unique=False)
    op.create_index(
        op.f("ix_track_status_session_id"), "track_status", ["session_id"], unique=False
    )
    op.create_table(
        "weather_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("session_time_seconds", sa.Float(), nullable=False),
        sa.Column("air_temp", sa.Float(), nullable=True),
        sa.Column("track_temp", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Float(), nullable=True),
        sa.Column("pressure", sa.Float(), nullable=True),
        sa.Column("wind_speed", sa.Float(), nullable=True),
        sa.Column("wind_direction", sa.Integer(), nullable=True),
        sa.Column("rainfall", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_weather_session_time",
        "weather_data",
        ["session_id", "session_time_seconds"],
        unique=False,
    )
    op.create_index(op.f("ix_weather_data_id"), "weather_data", ["id"], unique=False)
    op.create_index(
        op.f("ix_weather_data_session_id"), "weather_data", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_data_session_id"), table_name="weather_data")
    op.drop_index(op.f("ix_weather_data_id"), table_name="weather_data")
    op.drop_index("idx_weather_session_time", table_name="weather_data")
    op.drop_table("weather_data")
    op.drop_index(op.f("ix_track_status_session_id"), table_name="track_status")
    op.drop_index(op.f("ix_track_status_id"), table_name="track_status")
    op.drop_index("idx_track_status_session_time", table_name="track_status")
    op.drop_table("track_status")
    op.drop_index(
        op.f("ix_race_control_messages_session_id"), table_name="race_control_messages"
    )
    op.drop_index(
        op.f("ix_race_control_messages_id"), table_name="race_control_messages"
    )
    op.drop_index("idx_race_control_session_time", table_name="race_control_messages")
    op.drop_index("idx_race_control_session_driver", table_name="race_control_messages")
    op.drop_table("race_control_messages")
    op.drop_index(op.f("ix_laps_session_id"), table_name="laps")
    op.drop_index(op.f("ix_laps_id"), table_name="laps")
    op.drop_index(op.f("ix_laps_driver_id"), table_name="laps")
    op.drop_index("idx_laps_session_lap_number", table_name="laps")
    op.drop_index("idx_laps_session_driver", table_name="laps")
    op.drop_table("laps")
    # ### end Alembic commands ###
